# Generated by Django 4.1.1 on 2022-09-29 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson2", "0002_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="register_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(1000)]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
