# Generated by Django 4.1.1 on 2022-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson2", "0003_student_register_time_alter_lesson_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="education",
            field=models.CharField(
                choices=[
                    ("PR", "Primary"),
                    ("SE", "Secondary"),
                    ("JC", "Junior College"),
                    ("UN", "University"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
